services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: socialmedia
            DB_USERNAME: toby
            DB_PASSWORD: TobiasJensen20@mysql
        ports:
            - "8000:8000"
        depends_on:
            db:
                condition: service_healthy

    db:
        image: mysql:latest
        container_name: mysql_db
        environment:
            MYSQL_ROOT_PASSWORD: TobiasJensen20@mysql
            MYSQL_DATABASE: socialmedia
            MYSQL_USER: toby
            MYSQL_PASSWORD: TobiasJensen20@mysql
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
    db_data:
